version: '3.9'

services:
  vending-machine-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - vending-machine-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=wowSecurePassword
      - POSTGRES_DB=vending-machine-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - vending-machine-network
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - vending-machine-db
      - migrate
      - seed
    environment:
      - DATABASE_HOST=vending-machine-db
      - DATABASE_PORT=5432
      - DATABASE_USER=api
      - DATABASE_PASSWORD=wowSecurePassword
      - DATABASE_NAME=vending-machine-db
      - NODE_ENV=local
    networks:
      - vending-machine-network
  migrate:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: yarn typeorm migration:run --dataSource src/infrastructure/config/typeorm/typeorm.config.ts
    environment:
      - DATABASE_HOST=vending-machine-db
      - DATABASE_PORT=5432
      - DATABASE_USER=api
      - DATABASE_PASSWORD=wowSecurePassword
      - DATABASE_NAME=vending-machine-db
      - NODE_ENV=local
    depends_on:
      - vending-machine-db
    restart: no
  seed:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: yarn seed
    environment:
      - DATABASE_HOST=vending-machine-db
      - DATABASE_PORT=5432
      - DATABASE_USER=api
      - DATABASE_PASSWORD=wowSecurePassword
      - DATABASE_NAME=vending-machine-db
      - NODE_ENV=local
    depends_on:
      - vending-machine-db
      - migrate
    restart: no
    networks:
      - vending-machine-network
  web:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:8080
    networks:
      - vending-machine-network

volumes:
  vending-machine-db-data:
networks:
  vending-machine-network: